### ISSUE TITLE
Hive command ERROR

### ISSUE THREAD

**Issue by cmporeddy** [Tamilboomi/Project_FBI#1]
I tried to executive Hive command to insert Hbase data to Hive but it thorough an error.

as follows,

Command used: 

```
`CREATE EXTERNAL TABLE FBI_CRIME_TB(
ID INT,
Case_Number STRING,
Date STRING,
Block STRING,
IUCR STRING,
Primary_Type STRING,
Description STRING,
Location_Description STRING,
Arrest STRING,
Domestic STRING,
Beat STRING,
District STRING,
Ward STRING,
Community_Area STRING,
FBI_CODE STRING,
X_Coordinate STRING,
Y_Coordinate STRING,
Year INT,
Updated_On STRING,
Latitude STRING,
Longitude STRING,
Location STRING
)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES ("hbase.columns.mapping"=":key,CD:Case_Number,CD:Date,CD:Block,CD:IUCR,CD:Primary_Type,CD:Description,CD:Location_Description,CD:Arrest,CD:Domestic,CD:Beat,CD:District,CD:Ward,CD:Community_Area,CD:FBI_CODE,CD:X_Coordinate,CD:Y_Coordinate,CD:Year,CD:Updated_On,CD:Latitude,CD:Longitude,CD:Location")
TBLPROPERTIES("hbase.table.name"="H_FBI_CRIME","hbase.mapred.output.outputtable"="FBI_CRIME_TB");
`
```

Error :

```
`NoViableAltException(86@[2389:1: columnNameTypeOrConstraint : ( ( tableConstraint ) | ( columnNameTypeConstraint ) );])
    at org.antlr.runtime.DFA.noViableAlt(DFA.java:158)
    at org.antlr.runtime.DFA.predict(DFA.java:116)
    at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameTypeOrConstraint(HiveParser.java:34044)
    at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameTypeOrConstraintList(HiveParser.java:29840)
    at org.apache.hadoop.hive.ql.parse.HiveParser.createTableStatement(HiveParser.java:6662)
    at org.apache.hadoop.hive.ql.parse.HiveParser.ddlStatement(HiveParser.java:4295)
    at org.apache.hadoop.hive.ql.parse.HiveParser.execStatement(HiveParser.java:2494)
    at org.apache.hadoop.hive.ql.parse.HiveParser.statement(HiveParser.java:1420)
    at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:220)
    at org.apache.hadoop.hive.ql.parse.ParseUtils.parse(ParseUtils.java:74)
    at org.apache.hadoop.hive.ql.parse.ParseUtils.parse(ParseUtils.java:67)
    at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:616)
    at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1826)
    at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1773)
    at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1768)
    at org.apache.hadoop.hive.ql.reexec.ReExecDriver.compileAndRespond(ReExecDriver.java:126)
    at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:214)
    at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:239)
    at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:188)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:402)
    at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:821)
    at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:759)
    at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:683)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:239)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:153)
FAILED: ParseException line 4:0 cannot recognize input near 'Date' 'STRING' ',' in column name or constraint`
```

**Comment by tyagiaksh** [comment]
How did you solve above error?
